### ISSUE TITLE
Remove restriction in new pages

### ISSUE THREAD

**Issue by Apphiron** [mwtsn/restrict-content-by-role#1]
Everything is going well but I can't find a way to remove all restrictions on new pages and to remove all restriction in restricted pages (remove the padlock)

Thanks for your amazing plugin

**Comment by affiliatenow** [comment]
Same Here... All new pages are immediately locked, and I see no way to unlock for public access

**Comment by affiliatenow** [comment]
Same Here... I can make it public by setting the restriction on the page to "Sub-Content" only... but how do I get it to stop locking all newly created content. I want to manually choose which content is locked.

**Comment by mattwatsoncodes** [comment]
Hi there,

I spotted this bug after the latest WP core update.

I will be fixing it this week.

**Comment by mattwatsoncodes** [comment]
The latest push fixes this. I will be uploading this to the WP repo shortly.

**Comment by Apphiron** [comment]
Thanks Brou!!!
