### ISSUE TITLE
URL echo on multisite upon installation

### ISSUE THREAD

**Issue by djcowan** [mwtsn/restrict-content-by-role#16]
We installed plugin – no configuration settings changed.
**_**Page url is echoed on every page.**_**
Network activated or Site activated.
Wordpress Version 4.7.2
Plugin Version: 3.5

**Comment by mattwatsoncodes** [comment]
Thanks @djcowan I am looking at this today.

**Comment by mattwatsoncodes** [comment]
Hi @djcowan, sorry I cannot recreate this issue. Could you share a screenshot of what is going on please?
