### ISSUE TITLE
All pages become restricted when I add a new user role

### ISSUE THREAD

**Issue by nathanp** [mwtsn/restrict-content-by-role#3]
The plugin works great, but when I add a new user role to WP, **ALL** pages become restricted to be accessible to only that new role.

Can you push an update/temporary fix that does not automatically check new roles? I have hundreds of pages, and can’t afford to go through each page and uncheck a new role every time one is added.

Thanks!

**Comment by mattwatsoncodes** [comment]
Hi @nathanp, I'll look into this for you now. Hopefully there will be something in the next release for you.

**Comment by nathanp** [comment]
Thanks, @mwtsn!

**Comment by mattwatsoncodes** [comment]
Hi @nathanp,

The latest version lets you reset all permissions per role, so you will be able to remove all references to the offending new role. 

Let me know how you get on.

<img width="1232" alt="screenshot 2016-11-22 20 27 18" src="https://cloud.githubusercontent.com/assets/2066205/20540705/23f4102e-b0f2-11e6-96da-6ce85b65ef4e.png">
